DROP TABLE IF EXISTS Card;
DROP TABLE IF EXISTS Family;
DROP TABLE IF EXISTS CardGame;
DROP TABLE IF EXISTS Users;

CREATE TABLE IF NOT EXISTS CardGame(
  id INT UNSIGNED AUTO_INCREMENT,
  name VARCHAR(20),
  language VARCHAR(5),
  PRIMARY KEY(id),
  UNIQUE INDEX uniq_cardgame (name, language));

CREATE TABLE IF NOT EXISTS Family(
  id INT UNSIGNED AUTO_INCREMENT,
  name VARCHAR(20) NOT NULL,
  logo VARCHAR(20) DEFAULT NULL,
  cardGame INT UNSIGNED NOT NULL,
  PRIMARY KEY(id),
  FOREIGN KEY (cardGame) REFERENCES CardGame(id));

CREATE TABLE IF NOT EXISTS Card(
  id INT UNSIGNED AUTO_INCREMENT,
  content TEXT NOT NULL,
  description TEXT,
  family INT UNSIGNED NOT NULL,
  PRIMARY KEY(id),
  FOREIGN KEY (family) REFERENCES Family(id));

CREATE TABLE IF NOT EXISTS Users(
  pseudo VARCHAR(20),
  password CHAR(32) NOT NULL,
  email VARCHAR(255) NOT NULL,
  status CHAR(1) DEFAULT 0,
  PRIMARY KEY(pseudo),
  UNIQUE INDEX uniq_email (email(190)));
