DROP TABLE IF EXISTS Card;
DROP TABLE IF EXISTS CardFamily;
DROP TABLE IF EXISTS FamilyLogo;
DROP TABLE IF EXISTS CardGame;

CREATE TABLE IF NOT EXISTS CardGame(
  id INT UNSIGNED AUTO_INCREMENT,
  name VARCHAR(20),
  language VARCHAR(5),
  PRIMARY KEY(id),
  UNIQUE INDEX uniq_cardGame (name, language));

CREATE TABLE IF NOT EXISTS FamilyLogo(
  id INT UNSIGNED AUTO_INCREMENT,
  logo BLOB,
  PRIMARY KEY(id));

CREATE TABLE IF NOT EXISTS CardFamily(
  id INT UNSIGNED AUTO_INCREMENT,
  name VARCHAR(20) NOT NULL,
  logoId INT UNSIGNED,
  cardGameId INT UNSIGNED NOT NULL,
  PRIMARY KEY(id),
  FOREIGN KEY (cardGameId) REFERENCES CardGame(id) ON DELETE CASCADE,
  FOREIGN KEY (logoId) REFERENCES FamilyLogo(id));

CREATE TABLE IF NOT EXISTS Card(
  id INT UNSIGNED AUTO_INCREMENT,
  content TEXT NOT NULL,
  information TEXT,
  familyId INT UNSIGNED NOT NULL,
  PRIMARY KEY(id),
  FOREIGN KEY (familyId) REFERENCES CardFamily(id) ON DELETE CASCADE);
